"""foreign key delete cascade

Revision ID: d3a679236ac8
Revises: 9428a15fc654
Create Date: 2024-01-07 12:12:10.988791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a679236ac8'
down_revision: Union[str, None] = '9428a15fc654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bottles_shelf_id_fkey', 'bottles', type_='foreignkey')
    op.create_foreign_key(None, 'bottles', 'shelfs', ['shelf_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bottles', 'photo_link')
    op.drop_constraint('shelfs_cellar_id_fkey', 'shelfs', type_='foreignkey')
    op.create_foreign_key(None, 'shelfs', 'cellars', ['cellar_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shelfs', type_='foreignkey')
    op.create_foreign_key('shelfs_cellar_id_fkey', 'shelfs', 'cellars', ['cellar_id'], ['id'])
    op.add_column('bottles', sa.Column('photo_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bottles', type_='foreignkey')
    op.create_foreign_key('bottles_shelf_id_fkey', 'bottles', 'shelfs', ['shelf_id'], ['id'])
    # ### end Alembic commands ###
