"""cellar table modified

Revision ID: f61cfd53c08f
Revises: 5c9054c45506
Create Date: 2024-01-07 10:13:08.281088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61cfd53c08f'
down_revision: Union[str, None] = '5c9054c45506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cellars', 'available_shelfs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cellars', sa.Column('available_shelfs', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
